apiVersion: v1
kind: Service
metadata:
  name: node-api-svc
spec:
  type: NodePort
  selector:
    app: node-api-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 31080
